server:
  port: 8081 # Runs on port 8081 so it doesn't conflict with others

spring:
  application:
    name: fraud-producer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # Kafka stores data as bytes. We need to tell it how to convert our Java objects.
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # These prevent errors when the Consumer tries to read the JSON later
        spring.json.add.type.headers: false